service_type: host
addr: 172.25.250.10
hostname: clienta.lab.example.com
---
service_type: host
addr: 172.25.250.11
hostname: clientb.lab.example.com
---
service_type: host
addr: 172.25.250.12
hostname: serverc.lab.example.com
---
service_type: host
addr: 172.25.250.13
hostname: serverd.lab.example.com
---
service_type: host
addr: 172.25.250.14
hostname: servere.lab.example.com
---
service_type: host
addr: 172.25.250.16
hostname: serverg.lab.example.com
---
service_type: mon
placement:
  hosts:
    - clienta.lab.example.com
    - clientb.lab.example.com
    - serverc.lab.example.com
---
service_type: rgw
service_id: realm.zone
placement:
  hosts:
    - serverc.lab.example.com
    - clienta.lab.example.com
    - clientb.lab.example.com
---
service_type: mgr
placement:
  hosts:
    - serverc.lab.example.com
    - clienta.lab.example.com
    - clientb.lab.example.com
---
service_type: osd
service_id: mydrives
placement:
  hosts:
    - serverd.lab.example.com
    - servere.lab.example.com
    - serverg.lab.example.com
osds_per_device: 2
data_devices:
  paths:
    - /dev/vdb
    - /dev/vdc
    - /dev/vdd
